using NUnit.Framework;

using Vaultly.Identity.Api.Configuration;
using Vaultly.Identity.Application.Options;

namespace Vaultly.Identity.Application.Tests;

[TestFixture]
public sealed class JwtPrivateKeyResolverTests
{
    private string _temporaryDirectory = string.Empty;

    [SetUp]
    public void SetUp()
    {
        _temporaryDirectory = Path.Combine(Path.GetTempPath(), "vaultly-jwt-key-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_temporaryDirectory);
    }

    [TearDown]
    public void TearDown()
    {
        if (Directory.Exists(_temporaryDirectory))
        {
            Directory.Delete(_temporaryDirectory, recursive: true);
        }
    }

    [Test]
    public void Resolve_WhenPemFilePathIsRelative_LoadsKeyFromFile()
    {
        const string expectedPem = "-----BEGIN PRIVATE KEY-----\nkey-data\n-----END PRIVATE KEY-----";
        var relativePath = CreatePrivateKeyFile(".secrets\\identity-jwt-private-key.pem", expectedPem);

        var result = JwtPrivateKeyResolver.Resolve(
            new IdentityOptions { JwtPrivateKeyPemFilePath = relativePath },
            _temporaryDirectory,
            isDevelopment: false);

        Assert.Multiple(() =>
        {
            Assert.That(result.Pem, Is.EqualTo(expectedPem));
            Assert.That(result.SourceDescription, Does.Contain("identity-jwt-private-key.pem"));
        });
    }

    [Test]
    public void Resolve_WhenInlinePemAndFilePathAreBothConfigured_PrefersFile()
    {
        const string filePem = "file-pem";
        var relativePath = CreatePrivateKeyFile("keys\\jwt.pem", filePem);

        var result = JwtPrivateKeyResolver.Resolve(
            new IdentityOptions
            {
                JwtPrivateKeyPemFilePath = relativePath,
                JwtPrivateKeyPem = "inline-pem"
            },
            _temporaryDirectory,
            isDevelopment: false);

        Assert.That(result.Pem, Is.EqualTo(filePem));
    }

    [Test]
    public void Resolve_WhenPemFileDoesNotExistOutsideDevelopment_ThrowsInvalidOperationException()
    {
        Assert.That(
            () => JwtPrivateKeyResolver.Resolve(
                new IdentityOptions { JwtPrivateKeyPemFilePath = "missing\\jwt.pem" },
                _temporaryDirectory,
                isDevelopment: false),
            Throws.TypeOf<InvalidOperationException>()
                .With.Message.Contains("was not found"));
    }

    [Test]
    public void Resolve_WhenPemFileDoesNotExistInDevelopmentAndAutoGenerationEnabled_CreatesKeyFile()
    {
        const string relativePath = ".secrets\\identity-jwt-private-key.pem";

        var result = JwtPrivateKeyResolver.Resolve(
            new IdentityOptions
            {
                JwtPrivateKeyPemFilePath = relativePath,
                AutoGenerateDevelopmentJwtPrivateKey = true
            },
            _temporaryDirectory,
            isDevelopment: true);

        var fullPath = Path.Combine(_temporaryDirectory, relativePath);

        Assert.Multiple(() =>
        {
            Assert.That(File.Exists(fullPath), Is.True);
            Assert.That(result.Pem, Does.StartWith("-----BEGIN PRIVATE KEY-----"));
            Assert.That(File.ReadAllText(fullPath), Is.EqualTo(result.Pem));
            Assert.That(result.SourceDescription, Does.Contain("auto-generated development file"));
        });
    }

    [Test]
    public void Resolve_WhenPemFileDoesNotExistInDevelopmentAndAutoGenerationDisabled_ThrowsInvalidOperationException()
    {
        Assert.That(
            () => JwtPrivateKeyResolver.Resolve(
                new IdentityOptions
                {
                    JwtPrivateKeyPemFilePath = ".secrets\\identity-jwt-private-key.pem",
                    AutoGenerateDevelopmentJwtPrivateKey = false
                },
                _temporaryDirectory,
                isDevelopment: true),
            Throws.TypeOf<InvalidOperationException>()
                .With.Message.Contains("was not found"));
    }

    [Test]
    public void Resolve_WhenExistingPemFileIsEmpty_EvenInDevelopment_ThrowsInvalidOperationException()
    {
        var relativePath = CreatePrivateKeyFile(".secrets\\identity-jwt-private-key.pem", string.Empty);

        Assert.That(
            () => JwtPrivateKeyResolver.Resolve(
                new IdentityOptions
                {
                    JwtPrivateKeyPemFilePath = relativePath,
                    AutoGenerateDevelopmentJwtPrivateKey = true
                },
                _temporaryDirectory,
                isDevelopment: true),
            Throws.TypeOf<InvalidOperationException>()
                .With.Message.Contains("is empty"));
    }

    [Test]
    public void Resolve_WhenNoKeyIsConfigured_ThrowsInvalidOperationException()
    {
        Assert.That(
            () => JwtPrivateKeyResolver.Resolve(new IdentityOptions(), _temporaryDirectory, isDevelopment: false),
            Throws.TypeOf<InvalidOperationException>()
                .With.Message.Contains("Identity:JwtPrivateKeyPemFilePath"));
    }

    /// <summary>
    /// Creates a PEM file under the temporary test directory and returns the relative path used in configuration.
    /// </summary>
    private string CreatePrivateKeyFile(string relativePath, string content)
    {
        var fullPath = Path.Combine(_temporaryDirectory, relativePath);
        var directory = Path.GetDirectoryName(fullPath) ?? _temporaryDirectory;
        Directory.CreateDirectory(directory);
        File.WriteAllText(fullPath, content);
        return relativePath;
    }
}

