namespace Vaultly.Identity.Application.Options;

public sealed class IdentityOptions
{
    public string Issuer { get; set; } = string.Empty;
    public string Audience { get; set; } = string.Empty;
    public string PublicBaseUrl { get; set; } = string.Empty;
    public List<string> AllowedRedirectUris { get; set; } = [];
    public string JwtPrivateKeyPemFilePath { get; set; } = string.Empty;
    public bool AutoGenerateDevelopmentJwtPrivateKey { get; set; }
    public string JwtPrivateKeyPem { get; set; } = string.Empty;
    public int AccessTokenTtlMinutes { get; set; } = 15;
    public int RefreshTokenTtlDays { get; set; } = 30;
    public int AuthCodeTtlMinutes { get; set; } = 2;
    public int OAuthStateTtlMinutes { get; set; } = 10;
    public string? RefreshTokenCookieDomain { get; set; }
}