using Vaultly.Identity.Application.Options;

namespace Vaultly.Identity.Api.Configuration;

/// <summary>
/// Resolves the JWT signing key from configuration without logging secret material.
/// </summary>
public static class JwtPrivateKeyResolver
{
    /// <summary>
    /// Resolves the configured JWT signing key, preferring a file path over inline PEM content.
    /// </summary>
    public static ResolvedJwtPrivateKey Resolve(IdentityOptions options, string contentRootPath, bool isDevelopment)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentException.ThrowIfNullOrWhiteSpace(contentRootPath);

        if (!string.IsNullOrWhiteSpace(options.JwtPrivateKeyPemFilePath))
        {
            var resolvedPath = ResolvePath(contentRootPath, options.JwtPrivateKeyPemFilePath);

            if (!File.Exists(resolvedPath) && isDevelopment && options.AutoGenerateDevelopmentJwtPrivateKey)
            {
                var generatedPrivateKeyPem = CreateDevelopmentPrivateKeyFile(resolvedPath);
                return new ResolvedJwtPrivateKey(generatedPrivateKeyPem, $"auto-generated development file '{resolvedPath}'");
            }

            var privateKeyPem = ReadPrivateKeyFromFile(resolvedPath);
            return new ResolvedJwtPrivateKey(privateKeyPem, $"file '{resolvedPath}'");
        }

        if (!string.IsNullOrWhiteSpace(options.JwtPrivateKeyPem))
        {
            return new ResolvedJwtPrivateKey(options.JwtPrivateKeyPem, "configuration key 'Identity:JwtPrivateKeyPem'");
        }

        throw new InvalidOperationException(
            "A JWT signing key is required. Configure 'Identity:JwtPrivateKeyPemFilePath' to point to a PEM file, or set 'Identity:JwtPrivateKeyPem' directly.");
    }

    /// <summary>
    /// Resolves relative PEM file paths against the API content root.
    /// </summary>
    private static string ResolvePath(string contentRootPath, string configuredPath)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(configuredPath);

        return Path.IsPathFullyQualified(configuredPath)
            ? configuredPath
            : Path.GetFullPath(Path.Combine(contentRootPath, configuredPath));
    }

    /// <summary>
    /// Reads the PEM file contents and validates that the file exists and is not empty.
    /// </summary>
    private static string ReadPrivateKeyFromFile(string path)
    {
        if (!File.Exists(path))
        {
            throw new InvalidOperationException($"The JWT private key file '{path}' was not found.");
        }

        var privateKeyPem = File.ReadAllText(path).Trim();
        if (string.IsNullOrWhiteSpace(privateKeyPem))
        {
            throw new InvalidOperationException($"The JWT private key file '{path}' is empty.");
        }

        return privateKeyPem;
    }

    /// <summary>
    /// Generates a development RSA private key, persists it to disk, and reuses any concurrently-created file.
    /// </summary>
    private static string CreateDevelopmentPrivateKeyFile(string path)
    {
        var directory = Path.GetDirectoryName(path);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        using var rsa = System.Security.Cryptography.RSA.Create(2048);
        var privateKeyPem = rsa.ExportPkcs8PrivateKeyPem().Trim();

        try
        {
            using var fileStream = new FileStream(path, FileMode.CreateNew, FileAccess.Write, FileShare.None);
            using var writer = new StreamWriter(fileStream);
            writer.Write(privateKeyPem);
            writer.Flush();
            fileStream.Flush(flushToDisk: true);
            return privateKeyPem;
        }
        catch (IOException) when (File.Exists(path))
        {
            return ReadPrivateKeyFromFile(path);
        }
    }
}

/// <summary>
/// Represents the resolved JWT signing key and where it was loaded from.
/// </summary>
public sealed record ResolvedJwtPrivateKey(string Pem, string SourceDescription);

